version: "3.9"

services:

  weston:
    user: root
    privileged: true
    image: torizon/weston-imx8:4
    environment:
      - ACCEPT_FSL_EULA=1
    network_mode: host
    volumes:
      - type: bind
        source: /tmp
        target: /tmp
      - type: bind
        source: /dev
        target: /dev
      - type: bind
        source: /run/udev
        target: /run/udev

  acquisition:
    build: ./Acquisition
    container_name: acquisition
    cpuset: "2"
    privileged: true
    network_mode: host
    devices:
      - "/dev/i2c-3:/dev/i2c-3"
      - "/dev/ttymxc1:/dev/ttymxc1"
    volumes:
      - ./logs/acquisition:/logs:acquisition
    command: python3 main.py
    restart: unless-stopped

  control:
    build: ./Control
    container_name: control
    cpuset: "3"
    network_mode: host
    command: python3 control.py
    restart: unless-stopped
    depends_on:
      - acquisition

  telemetry:
    build: ./telemetry
    container_name: telemetry
    cpuset: "0,1"
    network_mode: host
    volumes:
      - ./telemetry:/app
      - ./logs:/logs
    command: python3 telemetry.py
    depends_on:
      - control
    restart: unless-stopped

volumes:
  shared-data:
