FROM --platform=linux/arm64 python:3.10-slim

RUN apt-get update && apt-get install -y \
    python3-smbus \
    i2c-tools

RUN pip install smbus2

WORKDIR /app
COPY bno055.py /app

CMD ["python3", "bno055.py"]
